export function emptyHostState() {
  return {
    serviceCount: 0,
    lastFamily: 0xffffffff,
    lastServiceId: 0,
    lastArgCount: 0,
    lastTopKind: 0,
    loadProgramCount: 0,
    fileQueryCount: 0,
    graphFormatCount: 0,
    graphRenderTextCount: 0,
    soundPlayCount: 0,
    soundServiceCount: 0,
    lastSoundServiceId: 0,
    lastSoundArgCount: 0,
    lastSoundTopKind: 0,
    lastSoundIntegerArgCount: 0,
    lastSoundMinIntegerArg: 0,
    lastSoundMaxIntegerArg: 0,
    lastAssetStringLen: 0,
    lastAssetStringHash: 0,
    lastAssetQueryServiceId: 0,
    lastAssetFound: 0,
    lastLoadedScriptStringLen: 0,
    lastLoadedScriptStringHash: 0,
    lastLoadedScriptFound: 0,
    soundAfterAssetQueryCount: 0,
  };
}
